AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 API - my.service::bookshelf-aws-spring
Globals:
  Api:
    EndpointConfiguration: REGIONAL
    BinaryMediaTypes:
      - 'multipart/form-data'

Resources:
  BookshelfAwsSpringFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: my.service.StreamLambdaHandler::handleRequest
      Runtime: java25
      CodeUri: .
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  BookshelfAwsSpringApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: BookshelfAwsSpringApi
